import type { NextPage } from 'next'
import Head from 'next/head'
import { Canvas, useThree  } from '@react-three/fiber'
import React from 'react'
import { useEffect, useRef } from 'react'
const Home: NextPage = () => {
  
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='w-screen bg-gray-800  h-screen'>
      <Canvas >
    <ambientLight intensity={1} />  
    <Model />
    </Canvas>
    </div>
    </div>
  )
}

import { Suspense } from 'react'
import { useLoader } from '@react-three/fiber'
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader'
import { useFrame } from '@react-three/fiber'
function Scene(){
  useThree(({camera}) => {
    camera.position.set(0,0,0);
  });
  return (<Canvas/>)
}
const Model: React.FC = () =>{
    const { scene, nodes, materials } = useLoader(GLTFLoader, '/commodore_pet.gltf'); 
    const mymesh = React.useRef();
    useFrame(({ clock }) => {
      mymesh.current.rotation.y = clock.getElapsedTime()/2
    })  

    return (
        <Suspense fallback={null}>
            <primitive castshadow castShadow receiveShadow  ref={mymesh} geometry={nodes} object={scene}
        scale={0.2} />
        </Suspense>
    )
}



export default Home
